CREATE OR REPLACE FUNCTION add_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','add_nums'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION mul_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','mul_nums'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION divide_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','divide_nums'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION sub_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','sub_nums'
LANGUAGE C STRICT;

CREATE FUNCTION hello_extension(text) RETURNS text
AS 'MODULE_PATHNAME', 'hello_extension'
LANGUAGE C STRICT;

CREATE FUNCTION hows_your_day(text) RETURNS text
AS 'MODULE_PATHNAME', 'hows_your_day'
LANGUAGE C STRICT;

CREATE FUNCTION reverse_string(text) RETURNS text
AS 'MODULE_PATHNAME', 'reverse_string'
LANGUAGE C STRICT;

CREATE FUNCTION capitalize_text(text)
RETURNS text
AS 'MODULE_PATHNAME', 'capitalize_text'
LANGUAGE C STRICT;

CREATE FUNCTION count_words(text)
RETURNS int
AS 'MODULE_PATHNAME', 'count_words'
LANGUAGE C STRICT;

CREATE FUNCTION factorial(int)
RETURNS int4
AS 'MODULE_PATHNAME', 'factorial'
LANGUAGE C STRICT;

CREATE FUNCTION is_prime(int)
RETURNS boolean
AS 'MODULE_PATHNAME', 'is_prime'
LANGUAGE C STRICT;

CREATE FUNCTION safe_divide(float8, float8)
RETURNS float8      
AS 'MODULE_PATHNAME', 'safe_divide'
LANGUAGE C STRICT;

CREATE FUNCTION power_float(float8, float8)
RETURNS float8
AS 'MODULE_PATHNAME', 'power_float'
LANGUAGE C STRICT;

CREATE FUNCTION arr_sum(float8[])
RETURNS float8
AS 'MODULE_PATHNAME', 'arr_sum'
LANGUAGE C STRICT;

CREATE FUNCTION arr_max(float8[])
RETURNS float8
AS 'MODULE_PATHNAME', 'arr_max'
LANGUAGE C STRICT;

CREATE FUNCTION log_message(text)
RETURNS void
AS 'MODULE_PATHNAME', 'log_message'
LANGUAGE C STRICT;

CREATE FUNCTION get_table_row_count(text)
RETURNS bigint
AS 'MODULE_PATHNAME', 'get_table_row_count'
LANGUAGE C STRICT;
