CREATE OR REPLACE FUNCTION add_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','add_nums'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION mul_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','mul_nums'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION divide_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','divide_nums'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION sub_nums(int,int)
RETURNS int
AS 'MODULE_PATHNAME','sub_nums'
LANGUAGE C STRICT;

CREATE FUNCTION hello_extension(text) RETURNS text
AS 'MODULE_PATHNAME', 'hello_extension'
LANGUAGE C STRICT;